
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fatckypxdqeaczndclbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhdGNreXB4ZHFlYWN6bmRjbGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMTU0MzMsImV4cCI6MjA1Njc5MTQzM30.KTn53_Yb2Gl-bnImUeOCMDEkeAa8iwM4E7diOwruJIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
